# Generated by Django 5.0.1 on 2024-02-09 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=10)),
                ('rpwd', models.CharField(max_length=15)),
                ('remail', models.CharField(max_length=20)),
                ('radd', models.TextField()),
                ('rphone', models.IntegerField(max_length=10)),
            ],
        ),
    ]
