# Generated by Django 4.2.3 on 2024-03-05 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_cartadd'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartadd',
            name='pquantity',
            field=models.CharField(default=1, max_length=2),
        ),
        migrations.AddField(
            model_name='cartadd',
            name='ptotalprice',
            field=models.CharField(default=50, max_length=10),
        ),
    ]
